---
# file: roles/galera/tasks/firewall.yml
- name: MySQL/MariaDB firewalld rule
  firewalld:
    port={{ fw_mysql }}
    permanent=true
    state=enabled
    immediate=true
  tags:
    - galera
    - galera-firewall

- name: IST replication firewalld rule
  firewalld:
    port={{ fw_mysql_ist }}
    permanent=true
    state=enabled
    immediate=true
  when: not galera_sst_method
  tags:
    - galera
    - galera-firewall

- name: SST replication firewalld rule
  firewalld:
    port={{ fw_mysql_sst }}
    permanent=true
    state=enabled
    immediate=true
  when: galera_sst_method
  tags:
    - galera
    - galera-firewall

- name: Galera firewalld rule
  firewalld:
    port={{ fw_galera }}
    permanent=true
    state=enabled
    immediate=true
  tags:
    - galera
    - galera-firewall

- name: xinetd firewalld rule
  firewalld:
    port={{ fw_xinetd }}
    permanent=true
    state=enabled
    immediate=true
  when: galera_pacemaker_support is defined and galera_pacemaker_support == true
  tags:
    - galera
    - galera-firewall
