---
# file: roles/galera/tasks/install.yml
- yum:
    list=mariadb-libs-5.5*x86_64
  register: pkg

- name: Removing old mariadb-libs package (RedHat family)
  package:
    name=mariadb-libs
    state=absent
  when: ansible_os_family == 'RedHat' and
        pkg.results[0].yumstate == 'installed'

- name: Installing MariaDB Galera packages
  package:
    name={{ item }}
    state=latest
  with_items:
    - "{{ galera_packages }}"
