---
# file: roles/galera/tasks/main.yml
- include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - galera
    - galera-bootstrap
    - galera-config 
    - galera-firewall
    - galera-repo
    - galera-reset
    - galera-secure
    - galera-selinux
    - galera-users
    - galera-install
    - galera-pacemaker

- include: reset.yml
  when: galera_reset_cluster and galera_reset_cluster == true

- include: repos.yml
- include: install.yml

- include: firewall.yml
  when: galera_firewalld and galera_firewalld == true

- include: config.yml
- include: secure.yml
- include: user.yml
- include: bootstrap.yml

- include: pacemaker.yml
  when: galera_pacemaker_support and galera_pacemaker_support == true
