---
# file: roles/galera/tasks/main.yml
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - galera
    - galera-bootstrap
    - galera-config 
    - galera-firewall
    - galera-repo
    - galera-reset
    - galera-secure
    - galera-selinux
    - galera-users
    - galera-install
    - galera-pacemaker

- name: Include OS family specific packages (since they were not defined)
  include_vars: "{{ ansible_os_family }}_packages.yml"
  tags:
    - galera
    - galera-bootstrap
    - galera-config 
    - galera-firewall
    - galera-repo
    - galera-reset
    - galera-secure
    - galera-selinux
    - galera-users
    - galera-install
    - galera-pacemaker
  when: galera_packages | length == 0

- include_tasks: reset.yml
  when: galera_reset_cluster is defined and
        galera_reset_cluster == true
  tags: [ galera, galera-reset ]

- include_tasks: repos.yml
  tags: [ galera, galera-repo ]

- include_tasks: install.yml
  tags: [ galera, galera-install ]

- include_tasks: firewalld.yml
  when: galera_firewalld is defined and
        galera_firewalld == true
  tags: [ galera, galera-firewall ]

- include_tasks: ufw.yml
  when: galera_ufw is defined and
        galera_ufw == true
  tags: [ galera, galera-firewall ]

- include_tasks: config.yml
  tags: [ galera, galera-config ]

- include_tasks: secure.yml
  tags: [ galera, galera-secure ]

- include_tasks: user.yml
  tags: [ galera, galera-users ]

- include_tasks: bootstrap.yml
  tags: [ galera, galera-bootstrap ]

- include_tasks: pacemaker.yml
  when: galera_pacemaker_support is defined and
        galera_pacemaker_support == true
  tags: [ galera, galera-pacemaker ]
