---
# file: roles/galera/tasks/repos.yml
- include_tasks: repos/Debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: repos/CentOS.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: repos/RedHat.yml
  when: ansible_distribution == 'RedHat'
