---
# file: roles/galera/tasks/repos/CentOS.yml
- name: Install MariaDB Galera repository (CentOS)
  copy:
    src=etc/yum.repos.d/MariaDB-centos.repo
    dest=/etc/yum.repos.d/
    mode=0644
- rpm_key:
    key=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    state=present

- name: Install Percona repository (CentOS)
  rpm_key:
    key=https://www.percona.com/downloads/RPM-GPG-KEY-percona
    state=present
- package:
    name={{ item }}
    state=present
  with_items: "{{ percona_package }}"
