---
# file: roles/galera/tasks/repos/RedHat.yml
- name: Install MariaDB Galera repository (RedHat)
  copy:
    src=etc/yum.repos.d/MariaDB-rhel.repo
    dest=/etc/yum.repos.d/
    mode=0644
- rpm_key:
    key=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    state=present

- name: Install yum-utils package (RedHat)
  package:
    name=yum-utils
    state=latest
    update_cache=yes

- name: Enable extras repository (RedHat)
  command:
    yum-config-manager --enable rhel-7-server-extras-rpms
